image: docker:stable 

services:
  - docker:23.0.4-alpine3.17

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  
  GIT_DEPTH: "0"  

stages:
  - build
  - sonar
  - deploy

build:
  stage: build
  script:
    - docker build -t my-service .
    - docker save my-service | gzip > my-service.tar.gz
  artifacts:
    paths:
      - my-service.tar.gz

sonar:
  stage: sonar
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - main

deploy:
  stage: deploy
  image:
    name: hashicorp/terraform:latest
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  services:
    - name: localstack/localstack
      alias: localstack
  before_script:
    - rm -rf .terraform
    - terraform --version
    - terraform init
  script:
    - terraform apply -auto-approve
  after_script:
    - terraform destroy
  environment:
    name: localstack